### ISSUE TITLE
231001: Migration to Quatro

### ISSUE THREAD

**Issue by maehr** [maehr/academic-pandoc-template#38]
**Is your feature request related to a problem? Please describe.**

Lua-filters are being retired. See https://github.com/pandoc/lua-filters

**Describe the solution you'd like**

To migrate your `academic-pandoc-template` repository to use `quarto-actions`, you'll need to do the following:

Steps:

1. **Add Quarto Configuration**: Create a `quarto.yml` file in your repository to specify the Quarto build settings. This is similar to your existing `Makefile`.

2. **GitHub Actions Workflow**: Create a `.github/workflows/quarto-publish.yml` file in your repository. You can base it on the example from `quarto-actions`:

    ```yaml
    name: Quarto Publish

    on:
      push:
        branches:
          - main

    jobs:
      publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: quarto-dev/quarto-actions/setup@v1
        - uses: quarto-dev/quarto-actions/render@v1
        - uses: quarto-dev/quarto-actions/publish@v1
          with:
            publish_dir: _site
    ```

3. **Dependencies**: If your project relies on specific system dependencies, you might need to add a step in the GitHub Actions workflow to install them.

4. **Test Locally**: Before pushing the changes, test the Quarto build locally to make sure everything works as expected.

5. **Push and Monitor**: Once you're confident, push the changes to GitHub and monitor the Actions tab to ensure the workflow runs successfully.

Notes:

- The `quarto-actions` repository provides various examples for different use-cases like freezing code, specifying dependencies, etc. You might want to look into those based on your project's needs.
  
- The `quarto-actions` repository uses three main actions: `setup`, `render`, and `publish`. These are specified in the `action.yml` files within their respective directories.

**Describe alternatives you've considered**

None

**Additional context**

None
